### ISSUE TITLE
Allow users to pass in additional dependencies to update-pkgdown

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-ost/ghactions4r#7]
**Issue**
I got following error when using [update-pkgdown.yml](https://github.com/nmfs-fish-tools/ghactions4r/blob/main/.github/workflows/update-pkgdown.yml).

```
Error: Error: The `rsconnect` package is required to find published tutorials
Backtrace:
    █
 1. └─pkgdown::deploy_to_branch(new_process = FALSE)
 2.   └─pkgdown::build_site_github_pages(...)
 3.     └─pkgdown::as_pkgdown(pkg, override = list(destination = dest_dir))
 4.       └─pkgdown:::package_tutorials(pkg, meta)
 5.         └─pkgdown:::find_tutorials(path(path, "vignettes", "tutorials"))
 6.           └─rlang::check_installed("rsconnect", "to find published tutorials")
Warning message:
In readLines(con) : incomplete final line found on './_pkgdown.yml'
11 Removing worktree 11111111111111111111111111111111111111111111111111111111111
Running git worktree remove /tmp/RtmpE5B0kw/file2c4a3076d072
Execution halted
Error: Process completed with exit code 1.
```

**Potential solution**
I added rsconnect under r-lib/actions/setup-r-dependencies@v1 and the rsconnect error disappeared, but I am not sure if rsconnect is a required extra-package that is needed to be added to the reusable workflow for updating pkgdown sites with learnr tutorials.

```
- uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            rsconnect
          needs: website
```

**Comment by k-doering-NOAA** [comment]
I think you are right about what is going on. I think also if there are additional dependencies in vignettes or tutorials that aren't package dependencies, the user need a way to pass them in. Maybe we could allow a user input so that users can pass in a string of extra package names? Open to other ideas about how to do this, though.

**Comment by Bai-Li-NOAA** [comment]
Thanks for the feedback! I think passing in a string of extra package names is a great idea. The two links below might be helpful:
1) usage of extra-packages: https://github.com/r-lib/actions/tree/v2/setup-r-dependencies
2) modify yml files using R: https://github.com/maxheld83/ghactions

**Comment by k-doering-NOAA** [comment]
Thanks @Bai-Li-NOAA ! This is on my to-do list

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA after thinking more about this and doing some googling, I think it might be more appropriate to include all dependencies needed to build vignettes in SUGGESTS section of the DESCRIPTION file rather than allowing users to pass in their own string of custom packages. I think this may also make sense for packages with learnr tutorials?

For example, this seems to be the strategy used in tidyverse: https://r-pkgs.org/description.html#whether-and-how-to-guard-in-a-test

What do you think about this? And would you mind trying to see if adding  pkgdown and rsconnect as suggests will allow the workflow to run as is?

**Comment by Bai-Li-NOAA** [comment]
Thanks for sharing the strategy link. It is very helpful. For the nmfspalette package, rsconnect is not a formal dependency. Maybe I can add a `Config/Needs/website` section in DESCRIPTION file. It would help specify packages that are not a formal dependency, but that must be included in order to build the package's website.  For example,

```
in DESCRIPTION                  in .github/workflows/update-pkgdown.yaml
--------------------------      ---------------------------------
Config/Needs/website:           - uses: r-lib/actions/setup-r-dependencies@v1
    rsconnect                    with:
                                    extra-packages: pkgdown
                                    needs: website
```
I am happy to test it and I will keep you posted.

**Comment by k-doering-NOAA** [comment]
That makes sense, thanks, Bai! It seems like the Config/Needs/website is a standard way of including needs for a website?

I think it makes sense to make the change in update-pkgdown as you show above, as then we can direct users to put additional website dependencies in the DESCRIPTION file, rather than in the gh actions file.

**Comment by k-doering-NOAA** [comment]
It looks like the necessary specification is already available in the update-pkgdown job; could you test and let me know if it works, @Bai-Li-NOAA ?

Also, if there are still issues, one thing we could try is switching to `@v2` tags for r-lib/actions steps; it looks like that just came out recently, and I read a thread while looking into this issue suggesting that it could solve some bugs with downloading dependencies of dependencies.

**Comment by Bai-Li-NOAA** [comment]
Sounds great. Will test it tomorrow and let you know.

**Comment by Bai-Li-NOAA** [comment]
Adding a `Config/Needs/website` section in DESCRIPTION file works well and you do not need to change anything in the update-pkgdown yaml file.

**Comment by k-doering-NOAA** [comment]
Great! I'm closing this, since all the functionality is there. The need to write more documentation is in #9
